### ISSUE TITLE
Custom modules

### ISSUE THREAD

**Issue by sobolevn** [softwarefactory-project/dhall-ansible#13]
Hi! Thanks a lot for writting this!

I am currently wondering how one should work with custom `ansible` modules? 
For example, you can install something from `ansible-galaxy` and then use it like `foo: prop=1`

How can we do that with `dhall-ansible`? Should we create a new `Type` definition and extend existing one with a new `module`?

**Comment by TristanCacqueray** [comment]
That seems correct, you would need to extend the `Task.Type` using the `//\\` operator, here is an example ^
