### ISSUE TITLE
Ansible.Play.serial should be Optional Natural

### ISSUE THREAD

**Issue by wfranzini** [softwarefactory-project/dhall-ansible#15]
The ansible documentation seems to suggest that serial should be ``Optional Natural``, not ``Optional (List Text)``
https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html#setting-the-batch-size-with-serial

**Comment by TristanCacqueray** [comment]
It seems like `Optional (List Text)` should cover all the possible serial values, for example this seems to be a valid:

```yaml
serial:
  - "10%"
  - "20%"
```

To use a single natural, couldn't you use `serial = Some [ Natural/show 42 ]` ?

**Comment by wfranzini** [comment]
Tristan de Cacqueray <notifications@github.com> writes:

> It seems like `Optional (List Text)` should cover all the possible
> serial values, for example this seems to be a valid:
>
> ```yaml
> serial:
>   - "10%"
>   - "20%"
> ```
>
> To use a single natural, couldn't you use `serial = Some [ Natural/show 42 ]` ?

You are right, I was not aware of the % form.

-- 
Walter Franzini

**Comment by TristanCacqueray** [comment]
It doesn't seem like worth it to support a different type for the serial value, otherwise please re-open the issue.
