### ISSUE TITLE
Package.dhall and package.dhall

### ISSUE THREAD

**Issue by Savemech** [softwarefactory-project/dhall-ansible#18]
Hi there, could we rename one of them to be able to work for people that does not work on case-sensitive  filesystems
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Ansible/Package.dhall'
  'Ansible/package.dhall'
```

**Comment by TristanCacqueray** [comment]
Thank you for the feedback, version 0.2.2 should be fixed: https://github.com/softwarefactory-project/dhall-ansible/blob/0.2.2/Ansible/package.dhall
