### ISSUE TITLE
Task ansible.builtin.import_task (and a few others) has the wrong type

### ISSUE THREAD

**Issue by daniels** [softwarefactory-project/dhall-ansible#24]
The type for `ansible.builtin.import_task` is defined as follows:

https://github.com/softwarefactory-project/dhall-ansible/blob/5b5008d6dac9fef588cc5ac5deb969e7ec1d55bf/Ansible/Builtin/ImportTasks/Type.dhall#L1

This should probably be just `Text`.

If I supply a matching record:

```dhall

Ansible.Task::{
    import_tasks = Some { free-form = "my-tasks.yml" }
}
```

it generates the following YAML

```yaml
- import_tasks:
    free-form: my-tasks.yml
```

which Ansible says is invalid:

```
ERROR! Invalid options for import_tasks: free-form
```

Looking at the [Ansible-documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/import_tasks_module.html) I can only guess that they used a template for the parameters that didn't fit with this special case task so they wrote "free-form" in a parameter field to indicate that the parameter *was* free-form. Maybe you autogenerated the definition from this. See the examples in the documentation for how it actually is used

I can see that this is not the only Type with this parameter: https://github.com/softwarefactory-project/dhall-ansible/search?q=free-form

Some of the others could be fixed in the same way, while a few has the free-form as an alternative to a dictionary of normal parameters.

**Comment by daniels** [comment]
Aside, can I override the type for a field somehow? I know I can add missing fields by defining my own schema and merge it with the BaseTask through the BlockTask, but it failed when I tried to redefine an existing type.

**Comment by daniels** [comment]
An additional note - these `include_*`/`import_*` tasks are probably not very useful if/when your whole Ansible config is generated from Dhall. But they would be quite handy during gradual migration/refactoring.

**Comment by TristanCacqueray** [comment]
This is indeed an issue. I think we could make the type match Text when the only attribute is named free-form. Though I wonder if we should remove the schema as they can still be useful. On the other I don't think there is a way to change the Type, e.g. through `//\\`, thus we might want to remove them from the schema.

Let me propose to fix the schema first.

**Comment by TristanCacqueray** [comment]
I think #25 should cover most use-case. Let me know if that works for you, then I'll make a new release with the update.

**Comment by daniels** [comment]
I tested the change and my use case with import_tasks now works as expected. Thank you for fixing this so quickly. It really gives me confidence in the project.

**Comment by TristanCacqueray** [comment]
You are welcome, thank you for the feedback.

The change is now part of the 0.3.0 release, and you can use this url which has the frozen package:

```dhall
let Ansible =
      https://raw.githubusercontent.com/softwarefactory-project/dhall-ansible/0.3.0/package.dhall sha256:8a77a647b1278791ed1e25e7f5a276ae07a88cbfcb07bc4858dc834d1c261de8

in {=}
```
