### ISSUE TITLE
var with non string value?

### ISSUE THREAD

**Issue by singpolyma** [softwarefactory-project/dhall-ansible#8]
Is it possible to set a var (for use with a task like import_role) to a non-string value, such as a boolean?

**Comment by TristanCacqueray** [comment]
The current implementation for `vars` is a [Map Text Text](https://github.com/TristanCacqueray/dhall-ansible/blob/master/types/map_text.dhall) as it is the simplest thing to use. You could trick Ansible to use non-string value using Jinja expression:

```dhall
toMap { boolVar = "{{ true | bool }}" }
```

Though I don't think that's appropriate, and in another package I recently used the [JSON/Type](https://prelude.dhall-lang.org/JSON/Type) for such arbitrary vars object and that was not much more complex to use, here is an [example](https://github.com/softwarefactory-project/dhall-zuul/blob/ac2521a0deddce7834d806ab3243997a5321f1ce/examples/ansible-zuul-jobs.dhall#L85-L91). Thus I think it would be better to replace the current map_text with a JSON/Type.

**Comment by TristanCacqueray** [comment]
As part of adding support for ansible collection (see the [proposal](https://discourse.dhall-lang.org/t/adding-support-for-ansible-collections-to-dhall-ansible/415)), the `vars` and other arbitrary dictionaries are replaced with the dhall-lang Prelude `JSON/Type`. I'll close this issue when implemented.

**Comment by TristanCacqueray** [comment]
`vars` are now `JSON/Type`.
